'use strict';

export const combatStyleAdvantages = [
    { winnerRole: "defensive_zoner", loserRole: "dominant_offense", advantage: 5, reason: "{AttackerName}'s defensive zoning contained {DefenderName}'s raw aggression" },
    { winnerRole: "mentor_strategist", loserRole: "brawler_redemption", advantage: 7, reason: "{AttackerName}'s strategic wisdom guided {DefenderName}'s fiery impulsiveness" },
    { winnerRole: "disabler", loserType: "Bender", advantage: 15, reason: "{AttackerName}'s chi-blocking prowess rendered {DefenderName}'s bending useless" }
];

export const adjectiveToNounMap = {
    "pacifistic": "pacifism", "agile": "agility", "inventive": "inventiveness", "adaptable": "adaptability",
    "resourceful": "resourcefulness", "clever": "cleverness", "determined": "determination", "resilient": "resilience",
    "stubborn_resolve": "stubborn resolve", "immovable": "immovability", "disciplined_combatant": "disciplined combat",
    "formidable": "formidability", "precise": "precision", "eccentric": "eccentricity", "powerful": "power",
    "unpredictable": "unpredictability", "wise": "wisdom", "calm": "calmness", "ruthless": "ruthlessness",
    "arrogant": "arrogance", "intimidating": "intimidation", "compassionate": "compassion",
    "unwavering_determination": "unwavering determination", "exceptional_swordsman": "exceptional swordsmanship",
    "controlled_fury": "controlled fury", "firebending_prodigy": "firebending prowess",
    "master_tactician": "masterful tactics", "highly_manipulative": "manipulative skill",
    "exceptional_firebending_prowess": "exceptional firebending prowess", "indomitable_will": "indomitable will",
    "raw_power": "raw power", "fear-inducing_presence": "fear-inducing presence", "relentless": "relentlessness",
    "mad_genius_tactics": "mad genius tactics", "brilliant_strategist": "brilliant strategy",
    "ancient_wisdom": "ancient wisdom", "terrain_control": "terrain control",
    "exceptional_agility": "exceptional agility", "disables_benders": "chi-blocking prowess",
    "precise_strikes": "precise strikes", "unpredictable_movements": "unpredictable movements",
    "speed": "speed", "deadly_accuracy": "deadly accuracy", "high_precision": "high precision",
    "unflappable_demeanor": "unflappable demeanor", "ranged_dominance": "ranged dominance",
    "silent_approach": "silent approach", "masterful_strategist": "masterful strategy",
    "profound_wisdom": "profound wisdom", "lightning_redirection": "lightning redirection",
    "hidden_power": "hidden power", "exceptional_self-control": "exceptional self-control",
    "defensive_master": "defensive mastery", "evasive": "evasiveness", "pacifistic_tendencies": "pacifistic tendencies", 
    "prodigious_bending_talent": "prodigious bending talent", "exceptional_healing": "exceptional healing",
    "fierce_determination": "fierce determination", "unconventional_fighting_style": "unconventional fighting style",
    "seismic_perception": "seismic perception",
    "vulnerable_to_direct_bending_attacks": "vulnerability to direct bending attacks",
    "reliance_on_equipment": "reliance on equipment", "limited_close_combat": "limited close combat",
    "can_be_overwhelmed": "susceptibility to being overwhelmed", "physically_average": "average physical condition",
    "aversion_to_lethal_force": "aversion to lethal force", "direct_confrontation": "struggle in direct confrontation",
    "vulnerable_to_ground_traps": "vulnerability to ground traps", "less_offensive_power": "limited offensive power",
    "emotional_volatility": "emotional volatility", "vulnerable_to_fire": "vulnerability to fire",
    "reliance_on_water_source": "reliance on water source", "deep-seated_mental_instability": "deep-seated mental instability",
    "lack_of_compassion": "lack of compassion", "can_be_overconfident": "overconfidence",
    "over-reliance_on_offensive_power": "over-reliance on offensive power", "extreme_arrogance": "extreme arrogance",
    "underestimates_opponents": "underestimation of opponents", "lack_of_adaptability": "lack of adaptability",
    "poor_defensive_strategy": "poor defensive strategy", "underestimated": "being underestimated",
    "vulnerable_when_not_on_earth": "vulnerability when not on earth", "can_be_distracted": "susceptibility to distraction",
    "slow": "slowness", "vulnerable_if_immobilized": "vulnerability if immobilized", "fragile": "fragility",
    "direct_physical_confrontation": "struggle in direct physical confrontation", "crowd_control": "vulnerability to crowd control",
    "limited_to_ranged_attacks": "limitation to ranged attacks", "vulnerable_in_close_proximity": "vulnerability in close proximity",
    "emotionally_reserved": "emotional reservedness", "lack_of_close_combat_skills": "lack of close combat skills",
    "reluctance_to_engage_in_direct_combat": "reluctance to engage in direct combat",
    "underestimated_by_adversaries": "being underestimated by adversaries", "prefers_philosophy_to_fighting": "preference for philosophy over fighting",
    "can_be_paternalistic": "paternalistic tendencies", "rigid_adherence_to_tradition": "rigid adherence to tradition",
    "initial_arrogance": "initial arrogance", "limited_adaptability": "limited adaptability",
    "less_effective_in_open_terrain": "less effectiveness in open terrain", "reluctance_to_fight": "reluctance to fight",
    "pessimistic_outlook": "pessimistic outlook", "cannot_generate_lightning": "inability to generate lightning",
    "vulnerable_to_direct_assault": "vulnerability to direct assault", "emotional_instability": "emotional instability",
    "impulsiveness": "impulsiveness", "can_be_hot-headed": "hot-headedness",
    "air_rich": "abundant air currents", "vertical": "vertical terrain", "exposed": "open exposure",
    "water_rich": "abundant water", "ice_rich": "icy conditions", "slippery": "slippery footing",
    "cold": "cold environment", "urban": "urban environment", "dense": "dense environment",
    "earth_rich": "abundant earth", "cover_rich": "ample cover", "cramped": "cramped spaces",
    "sandy": "sandy terrain", "hot": "intense heat", "shifting_ground": "shifting ground",
    "plants_rich": "abundant plant life", "low_visibility": "low visibility",
    "industrial": "industrial setting", "enclosed": "enclosed spaces", "metal_rich": "abundant metal",
    "precarious": "precarious footing", "rocky": "rocky terrain", "high_altitude": "high altitude",
    "coastal": "coastal environment"
};